language: python
python:
  - "3.6"

install:
    - pip install -r requirements.txt
    - python setup.py build_ext --inplace

script:
- python3 -m pytest tests/

after-succes:
- bash <(curl -s https://codecov.io/bash)